SocialConclave/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
from blogs import views as blog_views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('about/', include('core.urls')),
    path('blogs/', include('blogs.urls')),
    path('register/', include('register.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "blogs"

urlpatterns = [
    path('', views.allblog, name="allblog"),
    path('<str:blogslug>/', views.eachblog, name="eachblog"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "core"

urlpatterns = [
    path('', views.overTheYears, name="overTheYears"),
    path('agendas', views.agendas, name="agendas"),
]

main/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView

app_name = 'main'

urlpatterns = [
    path('', views.home, name='landing-page'),
]

blogs/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=2000000000,  default="", blank=False)
    shortTitle = models.CharField(
        max_length=2000000000,  default="", blank=False)
    introPara = models.TextField(default="", blank=False)
    slug = models.CharField(max_length=2000000000,  default="", blank=False, primary_key = True)
    introimage = models.TextField(default="", blank=False)

    def __str__(self):
        return self.title + " : " + self.slug

blogs/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import JsonResponse, HttpResponse
from .models import Blog
import json
app_name = "core"


# def jsonitems(request):
#     blogs = serializers.serialize("json", Blog.objects.all().order_by('time'))
#     blogs = json.loads(blogs)
#     return JsonResponse(blogs, safe=False)


# def home(request):
#     return render(request, 'blogs/bloghome.html', {'blogs': [1, 2, 3, 4, 5]})


# def blogview(request, blog):
#     blogs = Blog.objects.filter(slug__icontains=blog).first()
#     return render(request, 'blogs/blog.html', {'blog': blogs})

def allblog(request):
    allblogs = Blog.objects.all()
    return render(request, 'blogs/allblogs.html', {'allblogs': allblogs})


def eachblog(request, blogslug):
    return render(request, f'blogs/{blogslug}.html')

blogs/templates/blogs/allblogs.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <title>Blogs | Social Conclave</title>
    <meta name="description" content="">
    <meta name="author" content="">r
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
        integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
        crossorigin="anonymous" />

    <link rel="preload" href="{% static 'images/sclogo.png' %}" as="image">
    <link rel="preload" href="{% static 'images/earthRing.png' %}" as="image">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'css/blogscss.css' %}">
    <link rel="stylesheet" href="{% static 'css/blogs.css' %}">

    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
    <link rel="shortcut icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">


    <style>
        .services-list .service-text {
            height: unset !important;
        }

        @media only screen and (max-width: 767px) {
            .mobheight {
                height: 501px;
            }

            .services-list .service-text {
                height: unset !important;
            }

            .row.section-header {
                margin: 6rem 25px 0 25px !important;
                padding: 0;
            }

            p {
                font-size: unset;
            }
        }
    </style>
</head>

<body id="top">

    <!-- Header -->
    <header class="s-header">
        <div class="header-logo">
            <a class="site-logo" href="{% url 'main:landing-page' %}">
                <div class="headlinelogo">
                    <canvas id="headlinelogocanvas"></canvas>
                    <img class="scEarth" src="{% static 'images/earthRing.png' %}" alt="Social Impact Logo" />
                </div>
                <img class="scLogotxt" src="{% static 'images/socialconclave.png' %}" alt="Homepage">
            </a>
        </div>
        <!-- PC Nav -->
        <nav id="bigone" class="header-nav1">
            <div class="header-nav__content1">
                <ul class="header-nav__list">
                    <li><a href="{% url 'main:landing-page' %}" title="home">Home</a></li>
                    <li><a href="https://www.socialconclave.com/#about" title="about">About Us</a></li>
                    <li><a href="{% url 'core:agendas' %}" title="agendas">Agendas</a></li>
                    <!-- <li><a href="{% url 'blogs:allblog' %}" title="blogs">Blogs</a></li> -->
                    <li class="current"><a class="smoothscroll" href="#superCoreTeam" title="our team">Our Team</a></li>
                </ul>
            </div>
        </nav>
        <!-- /PC Nav -->
        <!-- Mobile Nav -->
        <nav id="smallone" class="con" style="float:right;" onclick="myFunction();">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
        </nav>
        <!-- /Mobile Nav -->
    </header>
    <!-- /Header -->

    <!-- Mobile Menu -->
    <div id="myNav" class="ov">
        <div class="ov-content">
            <a href="{% url 'main:landing-page' %}" title="home" onclick="myFunction();">Home</a>
            <a href="https://www.socialconclave.com/#about" title="about" onclick="myFunction();">About Us</a>
            <a href="{% url 'core:agendas' %}" title="agendas" onclick="myFunction();">Agendas</a>
            <!-- <a href="{% url 'blogs:allblog' %}" title="blogs" onclick="myFunction();">Blog</a> -->
            <a class="smoothscroll" href="{% url 'core:overTheYears' %}" title="our team" onclick="myFunction();">Our
                Team</a>
        </div>
    </div>
    <!-- /Mobile Menu -->

    <section id="home" class="s-home target-section short-header" data-parallax="scroll"
        data-image-src="{% static 'images/Sky bg.jpg' %}" data-natural-width="3000" data-natural-height="2000"
        data-position-y="center">
        <div class="overlay"></div>
        <div class="shadow-overlay"></div>
        <div class="home-content">
            <div class="row home-content__main">
                <h3>Social Conclave</h3>
                <br>
                <h1 style="margin-bottom:0px;">
                    Blogs</h1>
                <div class="home-content__buttons">
                    <a href="{% url 'main:landing-page' %}" class="btn btn--stroke">Home</a>
                    <a href="{% url 'core:overTheYears' %}" class="btn btn--stroke">
                        More About Us
                    </a>
                </div>
            </div>
            <!--<div class="home-content__scroll">
                    <a href="#about" class="scroll-link smoothscroll">
                        <span>Scroll Down</span>
                    </a>
                </div>-->
            <!--<div class="home-content__line"></div>
            </div>-->
            <ul class="home-social">
                <li>
                    <a href="https://facebook.com/socialconclave"><i class="fab fa-facebook-f"
                            aria-hidden="true"></i><span>Facebook</span></a>
                </li>
                <li>
                    <a href="https://twitter.com/social_conclave"><i class="fab fa-twitter"
                            aria-hidden="true"></i><span>Twitter</span></a>
                </li>
                <li>
                    <a href="https://instagram.com/socialconclave"><i class="fab fa-instagram"
                            aria-hidden="true"></i><span>Instagram</span></a>
                </li>
                <li>
                    <a href="https://www.linkedin.com/company/socialconclave/"><i class="fab fa-linkedin-in"
                            aria-hidden="true"></i><span>LinkedIn</span></a>
                </li>
            </ul>
    </section>

    <section id="services" class="s-services">
        <div class="row section-header has-bottom-sep" data-aos="fade-up">
            <div class="col-full">
                <!-- <h3 class="subhead">What We Do</h3> -->
                <h1 class="display-2">The Conclave Blog</h1>
            </div>
        </div>
        <div class="row services-list block-1-2 block-tab-full containerblogs" id="remblock">

            {% for allblog in allblogs %}

            <div class="col-block card" data-aos="fade-up">
                <div class="card__header">
                    <img src="{% static 'images/' %}{{allblog.introimage}}" class="card__image" width="600">
                </div>
                <div class="card__body">
                    <h4>{{allblog.shortTitle}}</h4>
                    <p>{{allblog.introPara}}
                    </p>
                    <div class="card__footer">
                        <a href="{{allblog.slug}}" target="_blank">Read Article</a>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </section>

    <!-- Footer -->
    <footer>
        <div class="row footer-main">
            <div class="col-four tab-full left footer-subscribe">
                <h4>Let's talk about</h4>
                <p>Got an inquiry? Feel free to reach out to us! We're happy to discuss on it.</p>
                <ul class="contact-social">
                    <li>
                        <a href="https://facebook.com/socialconclave"><i class="fab fa-facebook-f"
                                aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="https://twitter.com/social_conclave"><i class="fab fa-twitter"
                                aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="https://instagram.com/socialconclave"><i class="fab fa-instagram"
                                aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/company/socialconclave/"><i class="fab fa-linkedin-in"
                                aria-hidden="true"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-three tab-full right footer-desc">
                <div class="footer-log"></div>
                <h4>Links</h4>
                <ul>
                    <li><a class="smoothscroll" href="https://www.socialconclave.com/">Home</a></li>
                    <li><a href="{% url 'core:overTheYears' %}">Our Team</a></li>
                    <li><a href="{% url 'core:agendas' %}" title="agendas">Agendas</a></li>
                    <li><a href="{% url 'blogs:allblog' %}">Blogs</a></li>
                    <li><a href="https://www.socialconclave.com/#contact">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-five tab-full right footer-subscribe">
                <h4>Have any questions?</h4>

                <div class="cinfo-footer">
                    <h5>SUNANDAN DASGUPTA</h5>
                    <p>
                        <a href="tel:+919820934218">+91-9820934218</a><br>
                        <a href="mailto:sunandandasgupta.nmims@gmail.com">sunandandasgupta.nmims@gmail.com</a>
                    </p>
                </div>
            </div>
        </div>
        <div class=" row footer-bottom">
            <div class="col-twelve">
                <div class="go-top">
                    <a class="smoothscroll" title="Back to Top" href="#top">
                        <i class="icon-arrow-up" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
    <!-- /Footer -->


    <!--Preloader-->
    <div aria-hidden="true" class="pswp" role="dialog" tabindex="-1">
        <div class="pswp__bg"></div>
        <div class="pswp__scroll-wrap">
            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>
            <div class="pswp__ui pswp__ui--hidden">
                <div class="pswp__top-bar">
                    <div class="pswp__counter"></div><button class="pswp__button pswp__button--close"
                        title="Close (Esc)"></button> <button class="pswp__button pswp__button--share"
                        title="Share"></button> <button class="pswp__button pswp__button--fs
                               " title="Toggle fullscreen"></button> <button class="pswp__button pswp__button--zoom"
                        title="Zoom in/out"></button>
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                            <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div>
                </div><button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>
            </div>
        </div>
    </div>

    <div id="preloader">
        <div id="loader">
            <div class="scpreloader"><img src="{% static 'images/sclogo.png' %}" style="width:200px;"></div>
        </div>
    </div>
    <!--Preloader-->

    <script src="{% static 'js/5597-js-jquery-3.2.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/9959-js-plugins.js' %}"></script>
    <script src="{% static 'js/320-js-main.js' %}"></script>
    <script src="{% static 'js/nav.js' %}"></script>

    <!-- External Libraries -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.0.5/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/110/three.min.js"
        integrity="sha256-gSh8eotzb/CVvCREGPUNgIWuDnTYnZvVOQnRrP1eDjI=" crossorigin=" anonymous"></script>
    <script src="{% static 'js/earth.js' %}"></script>

    <script>
        $(window).scroll(function () {
            var sTop = $(this).scrollTop();
            if (sTop >= 1500) {
                $(".service-text").addClass("animmovedown");
            }

        });
    </script>
</body>

</html>

blogs/templates/blogs/bloghome.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- {% for blog in blogs %}
        {{blog}}
    {% endfor %} -->
</body>

</html>